# Generated by Django 3.1.7 on 2021-02-21 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTypeDefinition',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True)),
                ('definition', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedefinition_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedefinition_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Definition',
                'verbose_name_plural': 'Risk Definitions',
                'db_table': 'RiskTypesDefinitions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RiskTypeData',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedata_created_by', to=settings.AUTH_USER_MODEL)),
                ('risk_type_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.risktypedefinition')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedata_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Type Data',
                'verbose_name_plural': 'Risk Types Data',
                'db_table': 'RiskTypeData',
                'managed': True,
            },
        ),
    ]
