# Generated by Django 3.1.7 on 2021-02-22 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktypedata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedata_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risktypedata',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedata_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risktypedefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedefinition_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risktypedefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_risktypedefinition_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
