# Generated by Django 3.1.7 on 2021-02-27 17:59

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210222_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktypedefinition',
            name='definition',
            field=models.JSONField(validators=[api.validators.validate_schema]),
        ),
    ]
